### ISSUE TITLE
1.2.0 is a broken release

### ISSUE THREAD

**Issue by jasonkuhrt** [nbubna/Case#12]
At first I thought it was because of this https://github.com/nbubna/Case/commit/2ee18f3c19e3c4d1b8986b83e6e1c23a08094808#commitcomment-9465980 but I see that its not now. Instead it appears that the export type has changed from being an object of functions to a two-layer nested object structure, see:

![screen shot 2015-01-27 at 2 44 43 pm](https://cloud.githubusercontent.com/assets/284476/5925679/480c6d7e-a633-11e4-80b8-ae251245db6b.png)

**Comment by jasonkuhrt** [comment]
The bug is on this line https://github.com/nbubna/Case/blob/master/dist/Case.js#L129 See initial source and commit here https://github.com/nbubna/Case/commit/919b11058c0bf81226a89ec283428f4bd7b99b1e

**Comment by nbubna** [comment]
Yeah, i figured as much. First let me reiterate that i hate all module systems in JavaScript.

Second, that was to fix a problem when loading directly in the browser. I don't see how explicitly looking for 'module' in global (to prevent undefined reference warnings) would cause a structural change in the exports.

**Comment by jasonkuhrt** [comment]
@nbubna `this.module` is `false` where `module` is `true`.

**Comment by nbubna** [comment]
That is so stupid.

**Comment by jasonkuhrt** [comment]
By `false`/`true` I mean ***falsey***/***truthy***

**Comment by nbubna** [comment]
Well, i don't have time to go looking up the latest and greatest UMD stuff now. Feel free to take a shot at it and PR this, otherwise, i'll try to make time tonight or tomorrow.

**Comment by jasonkuhrt** [comment]
@nbubna In node all modules are wrapped already with a self-invoking function. I think its browsers that are magical and retarded by allowing implicit globals. But the entire JS community is fragmented with mostly lame tools etc. I feel your pain. In this case Node is a lot better than the browser though; you're just being bitten by optimizing for the crappier platform.

I'll see if I have time for a PR. For not I've just hard-pinned to `1.1.x`

**Comment by nbubna** [comment]
1) optimizing !== make functional
2) it sure looks like 'module' is functionally an implicit global in node, such that it's not clear how to test for its presence. At least in the browser, i know how to tell if something exists.

:)

**Comment by jasonkuhrt** [comment]
@nbubna If I remember `module` is implicit per module as it were. If it were truly global you'd have a whole bunch of other unholy problems.

**Comment by nbubna** [comment]
Yep, that's why i said "functionally", not "truly". It's magic. It is always present, like a global, but always a different object. And no way to inquire of any other scope/object whether it is there without breaking it.

It's very clever, of course. Solves a tough problem in a very clever way. But all too often, too clever == stupid. :)

Seriously, don't take offense. The node/io guys have made a very cool and useful thing. But nothing is sacrosanct. :)

**Comment by nbubna** [comment]
Ok, so would this work for you/node?

```
    var define = typeof define === "function" ? define : function(){};
    define(typeof module === "object" && module.exports ? module.exports = Case : this.Case = Case);
```

**Comment by jasonkuhrt** [comment]
@nbubna Yes I think so! If you make a commit I can pull from master and try it to verify at least in my use-case.

**Comment by nbubna** [comment]
Cool, i pushed it to master.

**Comment by jasonkuhrt** [comment]
@nbubna Seems good!

**Comment by jasonkuhrt** [comment]
Cut a release : )
