### ISSUE TITLE
Please add jsdoc for public interface

### ISSUE THREAD

**Issue by spat-ne-hochu** [nbubna/Case#17]
![case](https://cloud.githubusercontent.com/assets/7813784/16132871/a43dbeb2-3404-11e6-9396-366fb244d026.png)

is it no good, very no good =)

**Comment by nbubna** [comment]
Hey, sorry about the much belated response. Saw this, then promptly forgot about it for many months of other stuff. :(

What's the screenshot from? I don't use jsdoc, curious how you test this. :)

**Comment by thecotne** [comment]
i believe this is from [webstorm](https://www.jetbrains.com/webstorm/) 

but unresolved does not mean "it does not have jsDocs"

**Comment by nbubna** [comment]
Well, i haven't added jsdoc to the code, so it doesn't, i think. I'll check into  adding jsdoc, though i have doubts as to whether adding it is A) going to work for webstorm, given how that methods like `Case.kebab` are added dynamically, not statically declared. And B) of much value considering that these functions are fairly self-explanatory and the documentation is already short and simple.

**Comment by thecotne** [comment]
if you have jsdoc of function even without function itself webstorm will think that there is function ...

but i personally don't like nor jsdocs nor webstorm

**Comment by nbubna** [comment]
Interesting. So it doesn't walk the code to find docs, but just scans for docs, eh?

**Comment by thecotne** [comment]
it does all sorts of thinks scaning for function declarations for docs for exported vars etc. 

you mentioned Case.kabab is added dynamically i think that is reason why webstorm can't find function declaration

**Comment by nbubna** [comment]
Closing. JSDoc has not gained enough of my interest to be worth my personal effort. TypeScript typings are provided and recommended.

Reopen if you have a patch to add JSDoc.
