### ISSUE TITLE
MIT, GPL Viral License?

### ISSUE THREAD

**Issue by n8sabes** [nbubna/Case#21]
In doing a license audit, Case reports both MIT and GPL.

Anything that includes or links to GPL inherits GPL terms, therefore making the entire Case package viral. You also list MIT which is non-viral, but the GPL virally overrides the MIT terms.

Do you intend for Case to be GPL (viral), or MIT? Or, is Case subject to a sub-component / code snippet that carries GPL?

[Files in Case Referencing GPL](https://github.com/nbubna/Case/search?utf8=✓&q=gpl&type=)

**Comment by nbubna** [comment]
Case has no dependencies, and i, as the sole copyright owner have full authority to offer it under either or both licenses. As i understand it, the virality of the GPL is not at play here, it is founded on copyright and subservient to the copyright owner, not the other way around. When someone like myself releases a package under multiple licenses, the express intent it is to create an option of terms, not a hierarchy. Nothing in the GPL can or does overrule that.

**Comment by n8sabes** [comment]
Perfect, thanks.
