### ISSUE TITLE
Constant case not working

### ISSUE THREAD

**Issue by nmccready** [nbubna/Case#26]
Thanks for this great library! However, this is the first time I have run into a case were something was not as expected.

See the below:

```
const changeCase = require('change-case');
const Case = require('case');

console.log(Case.constant('crapP4')) // ===> 'CRAPP4'
console.log(changeCase.constant('crapP4')) // ===> 'CRAP_P4'
```

I believe changeCase is correct.

**Comment by nbubna** [comment]
Agreed. The number 4 should be treated like a lowercase letter here. Fix coming...
