### ISSUE TITLE
License field on npm showing "none" due to inappropriate LICENSE file name 

### ISSUE THREAD

**Issue by aymannedaa** [nbubna/Case#27]
On https://www.npmjs.com/package/case, license field is showing as "none", I think NPM cannot parse LICENSE-MIT file. Other variations such as LICENCE, LICENSE.md are accepted. 
I suggest renaming LICENSE-MIT to one of these variations if possible.

**Comment by nbubna** [comment]
Sounds reasonable. Care to contribute a PR? If not, i'll get to it at some point.

**Comment by aymannedaa** [comment]
Yes sure, I'll do a PR within this week.

Thanks.

**Comment by nbubna** [comment]
Thanks!
